---
- name: Pull docker image of calculator
  hosts: all
  tasks:
    - name: Pull junit devops image
      docker_image:
        name: rajatkumariiitb/cal-devops
        source: pull
    - name: Creating an empty file
        file:
          path: "/home/test_file.txt"
          state: touch